import matplotlib.pyplot as plt
import numpy as np

# Load results from the file
def load_results(filename):
    with open(filename, 'r') as file:
        results = [int(line.strip()) for line in file]
    return results

# Plot the results and show the average
def plot_results(results):
    avg_drinks = np.mean(results)  # Calculate the average
    total_drinks = len(results)  # Calculate the total number of drinks

    # Plot histogram
    plt.hist(results, bins=range(min(results), max(results) + 1), edgecolor='black', density=True)
    
    # Add a vertical line for the average
    plt.axvline(avg_drinks, color='red', linestyle='dashed', linewidth=2, label=f'Average: {avg_drinks:.2f}')
    
    plt.xlabel("Number of drinks")
    plt.ylabel("Frequency")
    plt.title(f"Busfahren Simulation ({total_drinks} Durchläufe)")
    plt.legend()
    plt.show()

if __name__ == "__main__":
    filename = "results.txt"  # This file should be generated by the C++ simulation
    results = load_results(filename)
    plot_results(results)
